### ISSUE TITLE
您好！我使用了你的方法构建全景图，但是现在跑不起来，全景图不显示，恼火得很，请问能帮忙看看吗？

### ISSUE THREAD

**Issue by inannan423** [loveskyhx/vuePanorama#1]
仓库地址：https://github.com/inannan423/csspano  ，npm run dev之后，threejs引擎在src\components\HelloWorld.vue界面，谢谢大佬，求带！🌹

**Comment by loveskyhx** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loveskyhx/vuePanorama"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 中午11:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [loveskyhx/vuePanorama] 您好！我使用了你的方法构建全景图，但是现在跑不起来，全景图不显示，恼火得很，请问能帮忙看看吗？ (Issue #1)





 
我现在没办法科学上网，如果你有什么问题可以看看我的掘金，给我私信或者留言

**Comment by inannan423** [comment]
我已经解决啦，谢谢你，博客很详细




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Copy the ***@***.***&gt;; 
发送时间: 2022年7月1日(星期五) 下午2:38
收件人: ***@***.***&gt;; 
抄送: "Always without ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [loveskyhx/vuePanorama] 您好！我使用了你的方法构建全景图，但是现在跑不起来，全景图不显示，恼火得很，请问能帮忙看看吗？ (Issue #1)





 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "loveskyhx/vuePanorama"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年7月1日(星期五) 中午11:35 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [loveskyhx/vuePanorama] 您好！我使用了你的方法构建全景图，但是现在跑不起来，全景图不显示，恼火得很，请问能帮忙看看吗？ (Issue #1) 
 
 
 
 
 
   
 我现在没办法科学上网，如果你有什么问题可以看看我的掘金，给我私信或者留言
